Web/Controllers/GraphController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Domain;
using Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class GraphController : Controller
    {
        private readonly GraphLine.IProvider _graphlineProvider;

        public GraphController(GraphLine.IProvider graphlineProvider)
        {
            _graphlineProvider = graphlineProvider;
        }

        public IActionResult Index(GraphFilters model)
        {
            return View("Index", model);
        }

        //public ActionResult LastReading()
        //{
        //    var lastTemperaturereading = _context.TemperatureReadings.Last();
        //    return Json(lastTemperaturereading);
        //}

        public ActionResult Temperature(GraphFilters filters)
        {            
            return Json(_graphlineProvider.Provide(filters));
        }       
    }
}

Web/Views/Graph/Index.cshtml
@using Web.Models
@model Web.Models.GraphFilters

@{

    ViewData["Title"] = "multigraph";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- load the d3.js library -->
<script src="http://d3js.org/d3.v4.min.js"></script>

<style>
    /* set the graph CSS */

    body { font: 12px Arial; }

    path {
        stroke: steelblue;
        stroke-width: 2;
        fill: none;
    }

    .axis path,
    .axis line {
        fill: none;
        stroke: grey;
        stroke-width: 1;
        shape-rendering: crispEdges;
    }

    .legend {
        font-size: 14px;
        /*font-weight: bold;*/
        text-anchor: middle;
    }
</style>

<h4>Graafik</h4>

<div>
    @Html.ActionLink("1 päev", "Index", "Graph", new GraphFilters(1, @Model.Symbol)) |
    @Html.ActionLink("1 nädal", "Index", "Graph", new GraphFilters(7, @Model.Symbol)) |
    @Html.ActionLink("1 kuu", "Index", "Graph", new GraphFilters(31, @Model.Symbol)) |
    @Html.ActionLink("1 aasta", "Index", "Graph", new GraphFilters(365, @Model.Symbol))
</div>

<div id="chart"></div>

Joone nimele vajutamine eemaldab selle joone graafikult


@*<script src="/js/MultiChart.js" type="text/javascript"></script>*@


<script>

    // Set the dimensions of the canvas / graph
    var margin = { top: 30, right: 50, bottom: 70, left: 50 },
        width = 600 - margin.left - margin.right,
        height = 300 - margin.top - margin.bottom;

    //var parseDate = d3.timeParse("%d/%m/%Y %H:%M");
    // Parse the date / time
    var parseDate = d3.timeParse("%Y-%m-%d %H:%M");

    // Set the ranges
    var x = d3.scaleTime().range([0, width]);
    var y = d3.scaleLinear().range([height, 0]);


    // Define the line
    var priceline = d3.line()
        .x(function(d) { return x(d.date); })
        .y(function(d) { return y(d.value); })
        .curve(d3.curveBasis);

    // Adds the svg canvas
    var svg = d3.select("#chart")
        .append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        .append("g")
        .attr("transform",
            "translate(" + margin.left + "," + margin.top + ")");

    // Get the data
    d3.json("Graph/Temperature?durationDays=@Model.DurationDays&symbol=@Model.Symbol", makeGraph);

    var zeroAxisHeight;

    function makeGraph(data) {

        //kirjutab konsoolile andmed
        //console.log(data);

        data.forEach(function(d) {
            d.date = parseDate(d.date);
            d.count = +d.value;
        });

        // Scale the range of the data
        var maxyValue = d3.max(data, function(d) { return d.value; });
        var minyValue = d3.min(data, function(d) { return d.value; });
 
        x.domain(d3.extent(data, function(d) { return d.date; }));
        y.domain([minyValue >0 && maxyValue >0 ? 0 : minyValue, minyValue <0 && maxyValue <0 ? 0 : maxyValue]);
//        y.domain([d3.min(data, function(d) { return d.value; }), d3.max(data, function(d) { return d.value; })]);

        //telje kõrguse leidmine et saaks selle panna 0 juurde kui 0 on graafikul olemas
        console.log(maxyValue);
        console.log(minyValue);

        if (maxyValue + minyValue == 0) {
            zeroAxisHeight = 0.5;
        } else if (maxyValue * minyValue < 0) {
            zeroAxisHeight = maxyValue / (Math.abs(minyValue) + Math.abs(maxyValue));
        } else if (maxyValue < 0 && minyValue < 0) {
            zeroAxisHeight = 0;
        } else {
            zeroAxisHeight = 1;
        }
    

        console.log(zeroAxisHeight);

        // Nest the entries by symbol
        var dataNest = d3.nest()
            .key(function(d) { return d.symbol; })
            .entries(data);

        // set the colour scale
        var color = d3.scaleOrdinal(d3.schemeCategory10);

        legendSpace = width / dataNest.length; // spacing for the legend

        // Loop through each symbol / key
        dataNest.forEach(function(d, i) {

            svg.append("path")
                .attr("class", "line")
                .style("stroke",
                    function() { // Add the colours dynamically
                        return d.color = color(d.key);
                    })
                .attr("id", 'tag' + d.key.replace(/\s+/g, '')) // assign an ID
                .attr("d", priceline(d.values));

            // Add the Legend
            svg.append("text")
                .attr("x", (legendSpace / 2) + i * legendSpace) // space legend
                .attr("y", height + (margin.bottom / 2) + 5)
                .attr("class", "legend") // style the legend
                .style("fill",
                    function() { // Add the colours dynamically
                        return d.color = color(d.key);
                    })
                .on("click",
                    function() {
                        // Determine if current line is visible
                        var active = d.active ? false : true,
                            newOpacity = active ? 0 : 1;
                        // Hide or show the elements based on the ID
                        d3.select("#tag" + d.key.replace(/\s+/g, ''))
                            .transition().duration(100)
                            .style("opacity", newOpacity);
                        // Update whether or not the elements are active
                        d.active = active;
                    })
                .text(d.key);

        });


        // Add the X Axis
        //Telje asukoht sõltub sellest kus on horisontaalne 0 telg
        if (zeroAxisHeight == 0) {
            svg.append("g")
                .attr("class", "axis")
                .attr("transform", "translate(0,0)")
                .call(d3.axisTop(x));
        } else {
            svg.append("g")
                .attr("class", "axis")
                .attr("transform", "translate(0, " + height + ")")
                .call(d3.axisBottom(x));

            svg.append("g")
                .attr("class", "axis")
                .attr("transform", "translate(0," + height * zeroAxisHeight + ")")
                .call(d3.axisBottom(x).ticks(0));
        }


        // Add the Y Axis
        svg.append("g")
            .attr("class", "axis")
            .call(d3.axisLeft(y));

        // Add second Y Axis
        svg.append("g")
            .attr("class", "axis")
            .attr("transform", "translate( " + width + ", 0 )")
            .call(d3.axisRight(y));

    };

</script>